version: "3.8"

services:
  expenses-service-db:
    container_name: expenses-service-db
    image: postgres:12
    ports:
      - "5433:5432"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - "app-expenses/.env.dev"

  users-service-db:
    container_name: users-service-db
    image: postgres:12
    ports:
      - "5434:5432"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - "app-users/.env.dev"

  localstack:
    container_name: localstack
    image: localstack/localstack:1.4.0
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack:/docker-entrypoint-initaws.d/"
