version: "3.8"

services:
  users-service-db:
    container_name: users-service-db
    image: postgres:12
    ports:
      - "5433:5433"
    tmpfs:
      - "/var/lib/postgresql/data"
    env_file:
      - "app-users/.env.local"
    command: -p 5433
