package com.github.arhor.aws.microservices.playground.overruns.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.util.Set;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "TrackingResult")
public class TrackingResult {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey(attributeName = "date")
    @DynamoDBTypeConverted(converter = LocalDateToStringTypeConverter.class)
    private LocalDate date;

    @DynamoDBAttribute(attributeName = "userIds")
    private Set<String> userIds;

    @DynamoDBVersionAttribute(attributeName = "version")
    private Long version;
}
