name: Expenses Service CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'app-expenses/**'
      - 'buildSrc/**'
      - 'build.gradle*'
      - 'gradle.properties'
      - 'settings.gradle*'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'app-expenses/**'
      - 'buildSrc/**'
      - 'build.gradle*'
      - 'gradle.properties'
      - 'settings.gradle*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Expenses Service app
        run: './gradlew :app-expenses:build'
